### PR TITLE
Update day5_2.rs

### PR DESCRIPTION
**Pull request by dmitris**
liked your solution! fixed a small typo in var name 😄

### CODE REVIEW

**Comment by ithinuel** [comment]
Thanks !

I updated the repo to add the License file.
If you agree to contribute under the same license (Apache 2.0), i'll be happy to merge your PR :D

**Comment by dmitris** [comment]
thanks @ithinuel - I agree to place my (trivial) contribution under the project license, Apache 2.0 😄

**Comment by ithinuel** [comment]
Arf, sorry about that conflict. Do you mind if I commit it and credit you in the commit log or do you prefer to rebase this PR ? :D 

((sorry for that fuss but licenses blahblahblah TT )

**Comment by dmitris** [comment]
rebased - thanks!

(if needed:
 I agree to place my (trivial) contribution under the project license, Apache 2.0 
)

**Pull request merged**
